- hosts: web_notes
  tasks:
   - name: "install common dep"
     yum:
       name: "{{ item }}"
       state: present
     become: yes
     with_items:
       - "git"
       - "mc"
   - name: "Install python env"
     yum:
       name: "{{ item }}"
       state: present
     become: yes
     with_items:
       - "python36"
       - "python36-pip"
       - "pytest"
   - name: "cloning repo"
     git:
       repo: https://github.com/domis14/animation_creator.git
       dest: ~/179647
   - name: "installing python packages"
     pip:
       name: "{{ item }}"
       executable: pip-3.6
     become: yes
     with_items:
       - "boto3"
       - "pytest"
       - "flask"
